// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rehdrcxghznldzrhgwfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlaGRyY3hnaHpubGR6cmhnd2Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2OTg0OTQsImV4cCI6MjA2MjI3NDQ5NH0.-99C065hgMTDaNWaxu9o7PQh86e3KiWSJeVdBxQ9z-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);